---
- name: Deploy Citadel AI Gateway
  hosts: api_gateway_servers
  become: yes
  vars:
    gateway_user: citadel-gateway
    gateway_home: /opt/citadel-gateway
    gateway_config_dir: /etc/citadel-gateway
    gateway_port: 8000
    log_dir: /var/log/citadel-gateway
    cors_origins: "*"
    model_map_verbose: false
    log_level: INFO
    fastapi_workers: 4

    ollama_nodes:
      - name: hx-llm-server-01
        host: 192.168.10.29
        port: 11434
      - name: hx-llm-server-02
        host: 192.168.10.28
        port: 11434

    model_mappings:
      "llama3.2:3b": "192.168.10.29:11434"
      "llama3:8b": "192.168.10.29:11434"
      "nous-hermes2:latest": "192.168.10.29:11434"
      "llama4:16x17b": "192.168.10.28:11434"
      "mistral:7b": "192.168.10.28:11434"
      "qwen3:8b": "192.168.10.28:11434"
      default: "192.168.10.28:11434"

  roles:
    - citadel_gateway
