---
- name: Citadel Alpha Phase 5 Database Deployment
  hosts: database_servers
  become: yes
  roles:
    - database-optimization

- name: Citadel Alpha Phase 5 Vector Database Deployment  
  hosts: vector_db_servers
  become: yes
  roles:
    - vector-database

- name: Citadel Alpha Phase 5 API Gateway Deployment
  hosts: api_gateway_servers
  become: yes
  roles:
    - api-gateway

- name: Citadel Alpha Phase 5 Web Interface Deployment
  hosts: web_servers
  become: yes
  roles:
    - web-interface
