# configs/ansible/deploy-prometheus-config.yml
---
- name: Deploy Prometheus Configuration for Node Exporter Targets
  hosts: metrics_servers
  become: true

  tasks:
    - name: Render and deploy Prometheus configuration
      template:
        src: templates/prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
        owner: root
        group: root
        mode: '0644'
      notify: restart prometheus

  handlers:
    - name: restart prometheus
      systemd:
        name: prometheus
        state: restarted
