# CX R&D Infrastructure Ansible Inventory
# 9-Server AI Research & Development Platform

all:
  children:
    devops:
      hosts:
        hx-dev-ops-server:
          ansible_host: 192.168.10.36
          server_role: devops
          services:
            - jenkins
            - terraform
            - ansible
    
    development:
      hosts:
        hx-dev-test-server:
          ansible_host: 192.168.10.35
          server_role: development
          ram: 125GB
          storage: 21.8TB
    
    llm_orchestration:
      hosts:
        hx-llm-orc-server:
          ansible_host: 192.168.10.34
          server_role: llm_orchestration
          ram: 32GB
          storage: 21.9TB
    
    database:
      hosts:
        hx-database-server:
          ansible_host: 192.168.10.33
          server_role: database
          ram: 16GB
          storage: 21.9TB
          services:
            - postgresql
            - redis
    
    vector_db:
      hosts:
        hx-vector-db-server:
          ansible_host: 192.168.10.32
          server_role: vector_database
          ram: 32GB
          storage: 21.8TB
          services:
            - qdrant
    
    web:
      hosts:
        hx-web-server:
          ansible_host: 192.168.10.31
          server_role: web
          ram: 16GB
          storage: 21.9TB
    
    api_gateway:
      hosts:
        hx-api-gateway-server:
          ansible_host: 192.168.10.30
          server_role: api_gateway
          ram: 16GB
          storage: 21.9TB
    
    test:
      hosts:
        hx-test-server:
          ansible_host: 192.168.10.29
          server_role: testing
          ram: 125GB
          storage: 21.8TB
    
    metrics:
      hosts:
        hx-metric-server:
          ansible_host: 192.168.10.28
          server_role: monitoring
          ram: 32GB
          storage: 21.9TB
          services:
            - prometheus
            - grafana

  vars:
    ansible_user: agent0
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    python_interpreter: /opt/citadel/env/bin/python
