---
# Phase 3: CX-Dev and CX-Test Server Deployment Playbook
# Citadel Alpha Infrastructure - Development & Testing Environment
# Target Servers: CX-Dev (192.168.10.33) & CX-Test (192.168.10.34)
# Timeline: August 1-7, 2025

- name: Deploy CX-Dev Server (Development Environment)
  hosts: development
  become: yes
  gather_facts: yes
  serial: 1
  
  pre_tasks:
    - name: Display target server information
      debug:
        msg: 
          - "Deploying to Development Server: {{ inventory_hostname }}"
          - "IP Address: {{ ansible_host }}"
          - "Server Role: {{ server_role }}"
          - "RAM: {{ ram }}"
          - "Storage: {{ storage }}"
    
    - name: Wait for server to be reachable
      wait_for_connection:
        timeout: 60
  
  roles:
    - common
    - python_env
    - development_tools
  
  post_tasks:
    - name: Verify development environment setup
      command: /opt/citadel/dev_env_check.sh
      register: dev_check_result
      become_user: agent0
    
    - name: Display development environment verification
      debug:
        var: dev_check_result.stdout_lines
    
    - name: Create deployment success marker
      copy:
        content: |
          CX-Dev Server Deployment Completed
          ==================================
          Deployment Date: {{ ansible_date_time.iso8601 }}
          Server: {{ inventory_hostname }}
          IP Address: {{ ansible_host }}
          Python Version: {{ ansible_python_version }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          
          Installed Components:
          - Python 3.12.3 Virtual Environment at /opt/citadel/env
          - Development tools and dependencies
          - VS Code Server (code-server) on port 8080
          - Docker and Docker Compose
          - Database clients (PostgreSQL, Redis)
          - Node.js and npm
          
          Services:
          - code-server.service (VS Code Server)
          
          Access:
          - SSH: ssh agent0@{{ ansible_host }}
          - VS Code: http://{{ ansible_host }}:8080 (password: citadel-dev-2025)
          
          Phase 3 Status: DEVELOPMENT SERVER DEPLOYED ✅
        dest: /opt/citadel/deployment_status.txt
        owner: agent0
        group: agent0
        mode: '0644'

- name: Deploy CX-Test Server (Testing Environment)
  hosts: test
  become: yes
  gather_facts: yes
  serial: 1
  
  pre_tasks:
    - name: Display target server information
      debug:
        msg: 
          - "Deploying to Test Server: {{ inventory_hostname }}"
          - "IP Address: {{ ansible_host }}"
          - "Server Role: {{ server_role }}"
          - "RAM: {{ ram }}"
          - "Storage: {{ storage }}"
    
    - name: Wait for server to be reachable
      wait_for_connection:
        timeout: 60
  
  roles:
    - common
    - python_env
    - testing_tools
  
  post_tasks:
    - name: Verify testing environment setup
      command: /opt/citadel/test_env_check.sh
      register: test_check_result
      become_user: agent0
    
    - name: Display testing environment verification
      debug:
        var: test_check_result.stdout_lines
    
    - name: Create deployment success marker
      copy:
        content: |
          CX-Test Server Deployment Completed
          ===================================
          Deployment Date: {{ ansible_date_time.iso8601 }}
          Server: {{ inventory_hostname }}
          IP Address: {{ ansible_host }}
          Python Version: {{ ansible_python_version }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          
          Installed Components:
          - Python 3.12.3 Virtual Environment at /opt/citadel/env
          - Testing frameworks (pytest, selenium, playwright)
          - Performance testing tools (locust)
          - Browser automation (Chromium, Playwright)
          - Docker and Docker Compose
          - Database clients (PostgreSQL, Redis)
          - Coverage and reporting tools
          
          Testing Capabilities:
          - Unit Testing with pytest
          - Integration Testing
          - Browser Automation with Selenium/Playwright
          - Performance Testing with Locust
          - Code Coverage Analysis
          - Automated Test Reporting
          
          Test Automation:
          - Run Tests: /opt/citadel/testing/run_tests.sh
          - Test Results: /opt/citadel/testing/results/
          - Test Reports: /opt/citadel/testing/reports/
          
          Access:
          - SSH: ssh agent0@{{ ansible_host }}
          
          Phase 3 Status: TESTING SERVER DEPLOYED ✅
        dest: /opt/citadel/deployment_status.txt
        owner: agent0
        group: agent0
        mode: '0644'

- name: Phase 3 Deployment Summary
  hosts: localhost
  gather_facts: no
  
  tasks:
    - name: Display Phase 3 completion summary
      debug:
        msg:
          - "=========================================="
          - "Phase 3: Development & Testing Deployment"
          - "=========================================="
          - "✅ CX-Dev Server (192.168.10.33): DEPLOYED"
          - "✅ CX-Test Server (192.168.10.34): DEPLOYED"
          - ""
          - "Development Environment Ready:"
          - "- Python 3.12.3 + Virtual Environment"
          - "- VS Code Server (http://192.168.10.33:8080)"
          - "- Docker & Development Tools"
          - ""
          - "Testing Environment Ready:"
          - "- Comprehensive Testing Framework"
          - "- Browser Automation & Performance Testing"
          - "- Automated Test Reporting"
          - ""
          - "Next Phase: AI Processing Tier (Phase 4)"
          - "Timeline: August 8-15, 2025"
          - "Target: LLM Servers (.28, .29, .31)"
