---
# Citadel Alpha - Phase 5 Inventory
# API Gateway & Web Services Deployment

all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/citadel_key
    ansible_python_interpreter: /usr/bin/python3
    
  children:
    phase5_servers:
      children:
        database_servers:
          hosts:
            cx-database:
              ansible_host: 192.168.10.35
              server_role: "primary_database"
              services:
                - postgresql
                - redis
                - monitoring
                
        vector_db_servers:
          hosts:
            cx-vector-database:
              ansible_host: 192.168.10.30
              server_role: "vector_database"
              services:
                - qdrant
                - backup_system
                - monitoring
                
        api_gateway_servers:
          hosts:
            cx-api-gateway:
              ansible_host: 192.168.10.39
              server_role: "api_gateway"
              services:
                - fastapi
                - nginx
                - load_balancer
                - monitoring
                
        web_servers:
          hosts:
            cx-web:
              ansible_host: 192.168.10.38
              server_role: "web_interface"
              services:
                - open_webui
                - nodejs
                - nginx
                - clerk_auth

    # Phase 4 LLM Dependencies (for reference)
    llm_servers:
      hosts:
        cx-llm-server-01:
          ansible_host: 192.168.10.29
          server_role: "chat_llm"
          ollama_port: 11434
          models:
            - "llama3.1:8b"
            - "qwen2.5:7b" 
            - "mistral:7b"
            
        cx-llm-server-02:
          ansible_host: 192.168.10.28
          server_role: "instruct_llm"
          ollama_port: 11434
          models:
            - "llama3.1:8b-instruct-q4_0"
            - "qwen2.5:7b-instruct"
            - "mistral:7b-instruct"
            
        cx-orchestration:
          ansible_host: 192.168.10.31
          server_role: "orchestration_embedding"
          ollama_port: 11434
          models:
            - "nomic-embed-text"

# Group Variables
database_servers:
  vars:
    postgresql_version: "15"
    redis_version: "7"
    backup_enabled: true
    
vector_db_servers:
  vars:
    qdrant_version: "1.8.0"
    storage_path: "/var/lib/qdrant"
    backup_enabled: true
    
api_gateway_servers:
  vars:
    python_version: "3.12"
    app_port: 8000
    workers: 4
    
web_servers:
  vars:
    nodejs_version: "18"
    app_port: 3000
    pm2_enabled: true
