# Definitive Ansible variables for the Citadel Gateway

# --- Gateway & Nginx Settings ---
gateway_port: 8000
log_level: INFO
cors_origins: "*"
gateway_user: "agent0"
gateway_home: "/opt/citadel-gateway"
log_dir: "/var/log/citadel-gateway"
model_map_verbose: false
fastapi_workers: 4          # <-- ADD THIS LINE (use 1 for a single worker, or 4 for multi-core)

# --- Backend Node Definitions ---
ollama_nodes:
  - name: hx-llm-server-01
    host: 192.168.10.29
    port: 11434
  - name: hx-llm-server-02
    host: 192.168.10.28
    port: 11434

# --- Explicit Model Routing Map ---
# This map is now 100% aligned with your `ollama list` output.
model_mappings:
  # Models on hx-llm-server-01 (192.168.10.29)
  "llama3.2:3b": "192.168.10.29:11434"
  "llama3:8b": "192.168.10.29:11434"

  # Models on hx-llm-server-02 (192.168.10.28)
  "llama4:16x17b": "192.168.10.28:11434"
  "mistral:7b": "192.168.10.28:11434"
  "qwen3:8b": "192.168.10.28:11434"

  # This model exists on both servers. We'll route it to server 1 by default.
  # You can change this to .28 if you prefer.
  "nous-hermes2:latest": "192.168.10.29:11434"