# HX R&D Infrastructure Server Inventory (Non-Encrypted)
# Updated: Aligned with actual hostnames and infrastructure layout

[hx_web_servers]
hx-web-server ansible_host=192.168.10.38 ansible_user=agent0 ansible_become=yes

[hx_api_servers]
hx-api-gateway-server ansible_host=192.168.10.39 ansible_user=agent0 ansible_become=yes

[hx_database_servers]
hx-sql-database-server ansible_host=192.168.10.35 ansible_user=agent0 ansible_become=yes

[hx_vector_servers]
hx-vector-db-server ansible_host=192.168.10.30 ansible_user=agent0 ansible_become=yes

[hx_llm_servers]
hx-llm-server-01 ansible_host=192.168.10.29 ansible_user=agent0 ansible_become=yes
hx-llm-server-02 ansible_host=192.168.10.28 ansible_user=agent0 ansible_become=yes

[hx_test_servers]
hx-test-server ansible_host=192.168.10.34 ansible_user=agent0 ansible_become=yes

[hx_devops_servers]
hx-dev-ops-server ansible_host=192.168.10.36 ansible_user=agent0 ansible_become=yes

[hx_metrics_servers]
hx-metrics-server ansible_host=192.168.10.37 ansible_user=agent0 ansible_become=yes

[hx_dev_servers]
hx-dev-server ansible_host=192.168.10.33 ansible_user=agent0 ansible_become=yes

# Phase 5 GPU Servers (Ed25519 SSH Keys)
[phase5_servers]
server1 ansible_host=192.168.10.101 ansible_user=agent0 ansible_become=yes ansible_ssh_private_key_file=~/.ssh/id_ed25519
server2 ansible_host=192.168.10.102 ansible_user=agent0 ansible_become=yes ansible_ssh_private_key_file=~/.ssh/id_ed25519
server3 ansible_host=192.168.10.103 ansible_user=agent0 ansible_become=yes ansible_ssh_private_key_file=~/.ssh/id_ed25519
server4 ansible_host=192.168.10.104 ansible_user=agent0 ansible_become=yes ansible_ssh_private_key_file=~/.ssh/id_ed25519
server5 ansible_host=192.168.10.105 ansible_user=agent0 ansible_become=yes ansible_ssh_private_key_file=~/.ssh/id_ed25519

# Logical groupings
[all_hx_servers:children]
hx_web_servers
hx_api_servers
hx_database_servers
hx_vector_servers
hx_llm_servers
hx_test_servers
hx_devops_servers
hx_metrics_servers
hx_dev_servers

[all_gpu_servers:children]
phase5_servers