#SPDX-License-Identifier: MIT-0
galaxy_info:
  author: CX R&D Infrastructure Team
  description: Deploy embedding models to Ollama on orchestration server
  company: CX Infrastructure
  license: MIT

  min_ansible_version: 2.12

  platforms:
  - name: Ubuntu
    versions:
    - "20.04"
    - "22.04"

  galaxy_tags:
    - ollama
    - embeddings
    - ai
    - ml
    - nlp

dependencies:
  - role: ollama_server
    when: ensure_ollama_installed | default(false)

  # Choose a valid license ID from https://spdx.org - some suggested licenses:
  # - BSD-3-Clause (default)
  # - MIT
  # - GPL-2.0-or-later
  # - GPL-3.0-only
  # - Apache-2.0
  # - CC-BY-4.0
  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.1

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  galaxy_tags: []
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
