#SPDX-License-Identifier: MIT-0
galaxy_info:
  author: CX R&D Infrastructure Team
  description: Deploy embedding models to Ollama on orchestration server
  company: CX Infrastructure
  license: MIT

  min_ansible_version: 2.12

  platforms:
  - name: Ubuntu
    versions:
    - "20.04"
    - "22.04"

  galaxy_tags:
    - ollama
    - embeddings
    - ai
    - ml
    - nlp

dependencies: []
  # Uncomment when ollama_server role is available:
  # - role: ollama_server
  #   when: ensure_ollama_installed | default(false)
