#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/node_exporter

- name: Download node_exporter archive
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.8.1/node_exporter-1.8.1.linux-amd64.tar.gz"
    dest: /tmp/node_exporter.tar.gz
    mode: '0644'

- name: Extract node_exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /opt/
    remote_src: yes
    creates: /opt/node_exporter-1.8.1.linux-amd64

- name: Symlink node_exporter binary
  file:
    src: /opt/node_exporter-1.8.1.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    state: link
    force: yes

- name: Create node_exporter systemd service
  copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Prometheus Node Exporter
      After=network.target

      [Service]
      User=nobody
      ExecStart=/usr/local/bin/node_exporter
      Restart=always

      [Install]
      WantedBy=default.target
  notify: Restart node_exporter

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start node_exporter
  systemd:
    name: node_exporter
    enabled: yes
    state: started
