#!/bin/bash
# CX R&D Infrastructure Health Check Script
# Generated by Terraform
# Updated: $(date)

set -e

echo "🏥 CX R&D Infrastructure Health Check"
echo "====================================="
echo "Checking ${length(servers)} servers..."
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Health check function
check_server() {
    local name=$1
    local ip=$2
    local port=$3
    local role=$4
    
    echo -n "Checking $name ($role) at $ip:$port... "
    
    if timeout 5 nc -z $ip $port 2>/dev/null; then
        echo -e "${GREEN}✅ ONLINE${NC}"
        return 0
    else
        echo -e "${RED}❌ OFFLINE${NC}"
        return 1
    fi
}

# Server checks
total_servers=0
online_servers=0

%{ for name, config in servers ~}
total_servers=$((total_servers + 1))
if check_server "${name}" "${config.ip_address}" "${config.port}" "${config.role}"; then
    online_servers=$((online_servers + 1))
fi
%{ endfor ~}

echo ""
echo "====================================="
echo "Health Check Summary:"
echo "Total Servers: $total_servers"
echo "Online: $online_servers"
echo "Offline: $((total_servers - online_servers))"

if [ $online_servers -eq $total_servers ]; then
    echo -e "${GREEN}🎉 All servers are online!${NC}"
    exit 0
else
    echo -e "${YELLOW}⚠️  Some servers are offline${NC}"
    exit 1
fi
