#!/bin/bash
# HX R&D Infrastructure Health Check Script
# Generated by Terraform on: ${timestamp()}

set -e

echo "🏥 HX R&D Infrastructure Health Check"
echo "====================================="
echo "Checking ${length(servers)} servers..."
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

check_server() {
    local name=$1
    local ip=$2
    local port=$3
    local role=$4

    echo -n "🔍 $name [$role] at $ip:$port... "
    if timeout 5 nc -z $ip $port 2>/dev/null; then
        echo -e "${GREEN}✅ ONLINE${NC}"
        return 0
    else
        echo -e "${RED}❌ OFFLINE${NC}"
        return 1
    fi
}

total=0
online=0

%{ for name, config in servers ~}
total=$((total + 1))
if check_server "${name}" "${config.ip_address}" "${config.port}" "${config.role}"; then
    online=$((online + 1))
fi
%{ endfor ~}

echo ""
echo "====================================="
echo "Summary:"
echo "Total: $total"
echo "Online: $online"
echo "Offline: $((total - online))"

if [ $online -eq $total ]; then
    echo -e "${GREEN}🎉 All servers are online!${NC}"
    exit 0
else
    echo -e "${YELLOW}⚠️  Some servers are offline${NC}"
    exit 1
fi
