# HX R&D Infrastructure - Dynamic Ansible Inventory
# Generated by Terraform on: ${timestamp()}

%{ for name, config in servers ~}
[${replace(config.role, "-", "_")}_servers]
${name} ansible_host=${config.ip_address} ansible_user=agent0 ansible_become=yes server_role=${config.role} server_port=${config.port}

%{ endfor ~}

# Logical group of all HX servers
[hx_infrastructure:children]
%{ for name, config in servers ~}
${replace(config.role, "-", "_")}_servers
%{ endfor ~}

[hx_infrastructure:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
deployment_environment=hx_rnd_infrastructure
project_name=citadel_ai_os
